### ISSUE TITLE
COPY table from stdin

### ISSUE THREAD

**Issue by temoto** [lxn/go-pgsql#14]
Hello.

Could you make it clear - is it possible to perform bulk load of data via COPY table from stdin; statement using go-pgsql? If yes, how?

P.S.: Thank you for this project. You really filled an empty space of pure Go implementation of such important protocol.

**Comment by lxn** [comment]
Hi, thanks for your nice words.

I'm afraid go-pgsql doesn't support this.

Maybe these days one of the other Go PostgreSQL drivers can do it?

**Comment by temoto** [comment]
I will look into implementing that. Some description of internal architecture would help.

**Comment by lxn** [comment]
Not sure if you are aware of https://github.com/bmizerany/pq, which seems to be the preferred pure Go PostgreSQL driver today.

Maybe it would be a better idea to implement this for that package, as I myself don't plan to work on go-pgsql any more besides bug fixes.

If there is a good reason to implement it for go-pgsql anyway, I will try to be of help.

**Comment by temoto** [comment]
Oh well, thank you. It is not listed on Go Projects wiki, so i thought i looked at all similar projects and chosen the least abandoned. :)
I don't think there is a "good reason" besides my curiosity and will to get something done now that i understood half your code. Great enter/exit logging, btw. So i'll try a bit more and if it doesn't work out, drop it altogether.

**Comment by temoto** [comment]
I like overall design. Thank you for insights.
