### ISSUE TITLE
decimal implemented as big.Rat instead of float64

### ISSUE THREAD

**Issue by brianoh** [lxn/go-pgsql#18]
I've written a test program for some of the database/sql packages. The others that I've tested to-date use a float64 for decimal values eg. "dbalance decimal(12,2) not null)" is scanned using a float64 as receiving value for the other 2 packages I've tested. From the testing that I've done, it would appear that this package uses big.Rat for decimal values. AFAIK and as determined from my testing to-date, float64 is perfectly adequate for decimal/currency values. In order to perform calculations, I convert them to an int64 to avoid rounding errors. I've partly altered my test program to cater for big.Rat,

I'm wondering if there is a particular reason for using big.Rat data-type instead of float64, and whether float64 may be more "standard"? I've partly implemented big.Rat in my test program, but thought it worth asking the question before completing the change, as float64 may have more general appeal.

**Comment by lxn** [comment]
Well, the PostgreSQL `decimal`/`numeric` type supports up to 131072 digits before the decimal point and up to 16383 digits after the decimal point. It seemed to me `big.Rat` would match that better than `float64`. If `float64` is sufficient on the Go side, then by all means a `double precision` should be used on the db side.

**Comment by brianoh** [comment]
Thanks for that info. I did a quick test using "double precision" for Postgres, and all appeared to work OK. I may fully-implement the decimal/big.Rat anyway (as an option), in case it turns out to be the "best" way to handle currencies in Postgres/Go. Currently I am converting the big.Rat to a double anyway, but that can easily be changed. I was initially very wary of doubles for obvious reasons, but they appear to be fine as a method of getting data into and out of a database. I'm not sure how Postgres handles doubles when used as currencies, so that may be a stumbling-block. Go appears to be OK providing doubles are not used for eg. addition/subtraction, so I convert them to int64. My tests indicate that this works OK providing one caters for truncation in Go when converting from double to int64.
