### ISSUE TITLE
Pools...

### ISSUE THREAD

**Issue by cbbrowne** [lxn/go-pgsql#6]
I'll observe that another Go/PG binding is on GitHub, https://github.com/jbarham/pgsql.go, which take the alternative approach of wrapping libpq.  

It handles the thread safety issue by implementing a connection pool mechanism.

I don't know if it's a better thing to try to merge code in one direction or another; I simply observe that it's worth taking a peek at it to see what's worth adapting in either direction.

**Comment by lxn** [comment]
Also there are probably some big changes ahead to fit with the exp/sql stuff.

I'm short on spare time at the moment though, but hope to continue working on go-pgsql before the end of the year.

In the meantime I will at least try to keep up with pull requests.

**Comment by andrewzeneski** [comment]
I have a modified version of that pool from jbarham/pgsql.go I am using with lnx/go-pgsql. If there is an interest I can submit a patch or pull request; just let me know.

**Comment by cbbrowne** [comment]
Sure, that's of interest.  And note that if a couple of people wind up hammering on the patch, that may make it an easier endeavor to get it integrated in, as there's presumably agreement as to its merits.

And I suppose that a followup step would be to add an implementation of pgpass (see src/interfaces/libpq/fe-connect.c, notably function PasswordFromFile(), for details).  That might be a fair thing for me to try to add.

**Comment by cbbrowne** [comment]
Actually, here's an attempt at .pgpass...

https://github.com/cbbrowne/go-pgsql/commit/b849b6f6b8556c533370dd47dc4d8b022db56fe0

**Comment by andrewzeneski** [comment]
Here is the pool integrated in with the same example from the original implementation (also migrated). 

https://github.com/andrewzeneski/go-pgsql/commit/04d0af82dcb974fc1599de09039617f5329aa6b3

FYI this was just an experiment and hasn't been tested much. I plan to start looking at the exp/sql package and seeing what will be needed to refactor go-pgsql to implement the driver interfaces.

**Comment by cbbrowne** [comment]
Cool, woiks!

I'll add to that with a makefile for the examples.

**Comment by samuel** [comment]
I fixed an issue with the pool where it would keep growing. The commit is at https://github.com/samuel/go-pgsql/commit/b9b3e3e4278c490165c92a65c1926d67e453c064  and I submitted a pull request to Andrew.

Thanks everyone for the work on this package.

**Comment by lxn** [comment]
Thanks everyone and sorry for taking so long.
